import {
  FaLaptopCode,
  FaHeartbeat,
  FaPlane,
  FaChartLine,
  FaBookOpen,
  FaSmile,
  FaUtensils,
  FaFilm,
  FaFutbol,
  FaFlask,
  FaPaintBrush,
  FaLandmark,
  FaGavel,
  FaLeaf,
  FaBuilding,
  FaGlobe,
  FaTshirt,
  FaCameraRetro,
  FaTools,
  FaBaby,
  FaEllipsisH,
} from "react-icons/fa";

import sampleImg from "./assets/travel.jpg";

const BLOG_CATEGORIES = [
  { name: "Technology", icon: FaLaptopCode, image: sampleImg },
  { name: "Health", icon: FaHeartbeat, image: sampleImg },
  { name: "Travel", icon: FaPlane, image: sampleImg },
  { name: "Finance", icon: FaChartLine, image: sampleImg },
  { name: "Education", icon: FaBookOpen, image: sampleImg },
  { name: "Lifestyle", icon: FaSmile, image: sampleImg },
  { name: "Food", icon: FaUtensils, image: sampleImg },
  { name: "Entertainment", icon: FaFilm, image: sampleImg },
  { name: "Sports", icon: FaFutbol, image: sampleImg },
  { name: "Science", icon: FaFlask, image: sampleImg },
  { name: "Art", icon: FaPaintBrush, image: sampleImg },
  { name: "History", icon: FaLandmark, image: sampleImg },
  { name: "Politics", icon: FaGavel, image: sampleImg },
  { name: "Environment", icon: FaLeaf, image: sampleImg },
  { name: "Business", icon: FaBuilding, image: sampleImg },
  { name: "Culture", icon: FaGlobe, image: sampleImg },
  { name: "Fashion", icon: FaTshirt, image: sampleImg },
  { name: "Photography", icon: FaCameraRetro, image: sampleImg },
  { name: "DIY", icon: FaTools, image: sampleImg },
  { name: "Parenting", icon: FaBaby, image: sampleImg },
  { name: "Other", icon: FaEllipsisH, image: sampleImg },
];

export { BLOG_CATEGORIES };